### ISSUE TITLE
Use bash script or Makefile to create new lab report directories?

### ISSUE THREAD

**Issue by aknierim** [pep-dortmund/toolbox-workshop-protocol-template#9]
@ChAr-De and I thought about how we could ensure that the students create new directories for each new lab report. One way would be to use a bash script or the already existing Makefile. Personally I would argue for the Makefile. However, @chrbeckm rightfully argues that this can confuse the students, so a bash script may be the way to go.

The underlying problem is, that even though we have precise instructions in the README, offering an easier method, i.e. just one command/script, may get more people to use the template as intended.

**Comment by maxnoe** [comment]
People should *learn*, not get a push-button-solve-everything provided by us

**Comment by aknierim** [comment]
> People should _learn_, not get a push-button-solve-everything provided by us

That's also true :)
